FROM node:20-alpine AS builder
WORKDIR /front
COPY wb-frontend/ ./
RUN npm ci && npm run build

FROM nginx:alpine AS frontend
COPY --from=builder /front/dist/ /usr/share/nginx/html
COPY wb-frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
